image: atlassian/default-image:2

options:
  docker: true

definitions:
  steps:
    - step: &tag-master
        name: Tag master commit
        script:
          - export VERSION_GIT=$(cat VERSION | head -1)
          - git tag -am "Tagging new release ${VERSION_GIT}" "${VERSION_GIT}"
          - git push origin "${VERSION_GIT}"
    - step: &build-default
        name: Build default
        script:
          - export IMAGE_NAME=dockerhub.ng-voice.com/opensips-base:$(echo $BITBUCKET_BRANCH | tr '/' '_')
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD dockerhub.ng-voice.com
          - docker build -t $IMAGE_NAME .
          - docker push $IMAGE_NAME
    - step: &build
        name: Build branches
        script:
          - export IMAGE_NAME=dockerhub.ng-voice.com/opensips-base:$(echo $BITBUCKET_BRANCH | tr '/' '_')-build-${BITBUCKET_BUILD_NUMBER}
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD dockerhub.ng-voice.com
          - docker build -t $IMAGE_NAME .
          - docker push $IMAGE_NAME
    - step: &build-tag
        name: Build tag
        script:
          - export IMAGE_NAME=dockerhub.ng-voice.com/opensips-base:${BITBUCKET_TAG}
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD dockerhub.ng-voice.com
          - docker build -t $IMAGE_NAME .
          - docker push $IMAGE_NAME
    - step: &build-pr
        name: Build pull request
        script:
          - export IMAGE_NAME=dockerhub.ng-voice.com/opensips-base:pr-${BITBUCKET_PR_ID}
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD dockerhub.ng-voice.com
          - docker build -t $IMAGE_NAME .
          - docker push $IMAGE_NAME

pipelines:
  default:
    - step: *build-default

  branches:
    master:
      - step: *tag-master
    feature/*:
      - step: *build
    hotfix/*:
      - step: *build
    bugfix/*:
      - step: *build
    release/*:
      - step: *build

  tags:
    '*':
      - step: *build-tag

  pull-requests:
    '**':
      - step: *build-pr
